home:
    pattern:  /
    defaults: { _controller: HillCMSResourceBundle:Default:index }
login:
    pattern:   /login
    defaults:  { _controller: HillCMSSecurityBundle:Security:login }
login_check:
    pattern:   /login_check
logout:
    pattern: /logout
jbrowse:
    pattern: /jbrowse
    defaults: { _controller: HillCMSResourceBundle:JBrowse:index }
blast:
    pattern: /blast
    defaults: { _controller: HillCMSResourceBundle:Blast:index }
blat:
    pattern: /blat
    defaults: { _controller: HillCMSResourceBundle:Blat:index }
blastlistener:
    pattern: /blastlistener
    defaults: { _controller: HillCMSResourceBundle:Blast:blastListener }

